import express from 'express';
import { GoogleGenAI } from '@google/genai';
import dotenv from 'dotenv';

dotenv.config();
const app=express();
const allowedOrigins=new Set(['https://agoy1602-coder.github.io','http://localhost:5173','http://localhost:4173']);
app.use((req,res,next)=>{const origin=req.headers.origin;if(origin&&allowedOrigins.has(origin)){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin')}res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');if(req.method==='OPTIONS')return res.sendStatus(204);next()});
app.use(express.json({limit:'50mb'}));app.use(express.urlencoded({extended:true,limit:'50mb'}));
function getGeminiApiKey(){return process.env.GEMINI_API_KEY||process.env.VOICECRAFT_API_KEY||''}
function getElevenLabsKey(){return process.env.ELEVENLABS_API_KEY||''}
let aiClient:GoogleGenAI|null=null;function getAI(){if(!aiClient){const key=getGeminiApiKey();if(!key)throw new Error('No Gemini API key is configured.');aiClient=new GoogleGenAI({apiKey:key})}return aiClient}
const audioCache=new Map<string,any>();const syncStore=new Map<string,any[]>();const deviceStore=new Map<string,any[]>();const feedbackStore:any[]=[];const notificationStore=new Map<string,any[]>();
app.get('/api/health',(_req,res)=>res.json({status:'ok',timestamp:Date.now(),geminiConfigured:!!getGeminiApiKey(),cloneProviderConfigured:!!getElevenLabsKey(),engine:'VoiceCraft Studio v2.5'}));

async function elevenCreateClone(name:string,sampleBase64:string,mimeType:string,notes:string){const key=getElevenLabsKey();if(!key)throw new Error('ELEVENLABS_API_KEY is not configured.');const form=new FormData();form.append('name',name);form.append('description',notes||`VoiceCraft instant voice clone for ${name}`);form.append('files[]',new Blob([Buffer.from(sampleBase64,'base64')],{type:mimeType||'audio/webm'}),'voice-sample.webm');const r=await fetch('https://api.elevenlabs.io/v1/voices/add',{method:'POST',headers:{'xi-api-key':key},body:form});const text=await r.text();let data:any;try{data=JSON.parse(text)}catch{data={error:text}}if(!r.ok||!data.voice_id)throw new Error(data?.detail?.message||data?.detail||data?.error||`ElevenLabs clone creation failed (HTTP ${r.status})`);return data.voice_id as string}
async function elevenTTS(voiceId:string,text:string,language:string,speed:number){const key=getElevenLabsKey();if(!key)throw new Error('ELEVENLABS_API_KEY is not configured.');const model=language==='en-US'||language==='en-GB'?'eleven_multilingual_v2':'eleven_multilingual_v2';const r=await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${encodeURIComponent(voiceId)}?output_format=mp3_44100_128`,{method:'POST',headers:{'xi-api-key':key,'Content-Type':'application/json'},body:JSON.stringify({text,model_id:model,voice_settings:{stability:.5,similarity_boost:.8,style:.15,use_speaker_boost:true,speed:Math.max(.7,Math.min(1.2,speed||1))}})});if(!r.ok){const t=await r.text();throw new Error(`ElevenLabs TTS HTTP ${r.status}: ${t.slice(0,300)}`)}return Buffer.from(await r.arrayBuffer()).toString('base64')}

app.post('/api/tts/generate',async(req,res)=>{try{const{text,voice='Kore',tone='professional',language='en-US',speed=1,pitch=1,customPromptModifier='',isClonedVoice=false,clonedProfileData=null}=req.body;if(!text||typeof text!=='string')return res.status(400).json({error:'Text prompt is required'});
 if(isClonedVoice&&clonedProfileData?.provider==='elevenlabs'&&clonedProfileData?.providerVoiceId){try{const audioBase64=await elevenTTS(clonedProfileData.providerVoiceId,text,language,speed);return res.json({success:true,audioBase64,format:'mp3_44100_128',sampleRate:44100,voiceUsed:clonedProfileData.name||'Cloned Voice',provider:'elevenlabs',voiceId:clonedProfileData.providerVoiceId,tone,language,characters:text.length,generatedAt:Date.now()})}catch(error:any){console.error('[VoiceCraft] ElevenLabs clone TTS error:',error?.message||error);return res.status(502).json({success:false,provider:'elevenlabs',error:`Cloned voice generation failed: ${(error?.message||String(error)).slice(0,300)}`})}}
 const validVoices=['Kore','Fenrir','Charon','Zephyr','Algenib','Gacrux'];const ttsVoice=validVoices.includes(voice)?voice:'Kore';const cacheKey=JSON.stringify({text:text.trim(),ttsVoice,tone,language,speed,pitch,isClonedVoice,clone:clonedProfileData?.id});if(audioCache.has(cacheKey))return res.json({success:true,...audioCache.get(cacheKey),fromCache:true});let delivery=`Speak naturally and expressively in ${language}, with a ${tone} tone`;if(ttsVoice==='Algenib')delivery+=' Use a clearly masculine, mature adult male voice with a low, gravelly chest resonance; do not use a feminine vocal character.';if(ttsVoice==='Gacrux')delivery+=' Use a clearly masculine, mature adult male voice with a grounded, warm, authoritative resonance; do not use a feminine vocal character.';if(ttsVoice==='Fenrir')delivery+=' Use a clearly masculine adult male voice with energetic, deep resonance; do not use a feminine vocal character.';if(ttsVoice==='Charon')delivery+=' Use a mature adult male narrator character with grounded, authoritative delivery; do not use a feminine vocal character.';if(speed<.8)delivery+=', slowly and clearly';if(speed>1.25)delivery+=', swiftly and clearly';if(customPromptModifier)delivery+=`. ${customPromptModifier}`;if(isClonedVoice&&clonedProfileData)delivery+=`. Match the supplied vocal profile: ${clonedProfileData.timbreDescription||clonedProfileData.name||'custom voice'}.`;
 const response=await getAI().models.generateContent({model:'gemini-3.1-flash-tts-preview',contents:[{parts:[{text:`${delivery}:\n\n"${text}"`}]}],config:{responseModalities:['AUDIO'],speechConfig:{voiceConfig:{prebuiltVoiceConfig:{voiceName:ttsVoice}}}}});const audioBase64=response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;if(!audioBase64)return res.status(502).json({success:false,useClientFallback:false,error:'Gemini returned no audio data.'});const payload={audioBase64,format:'pcm_24khz',sampleRate:24000,voiceUsed:ttsVoice,tone,language,characters:text.length,generatedAt:Date.now()};if(audioCache.size>=100)audioCache.delete(audioCache.keys().next().value as string);audioCache.set(cacheKey,payload);res.setHeader('Cache-Control','no-store');res.json({success:true,...payload});
 }catch(error:any){const msg=error?.message||String(error);const quota=error?.status==='RESOURCE_EXHAUSTED'||error?.code===429||/429|quota|resource_exhausted/i.test(msg);console.error('[VoiceCraft] TTS error:',msg);res.status(quota?429:502).json({success:false,quotaExceeded:quota,useClientFallback:quota,error:quota?'Gemini TTS rate limit or quota reached.':`TTS provider error: ${msg.slice(0,300)}`})}});

function heuristic(name:string,notes=''){const s=`${name} ${notes}`.toLowerCase();const fem=['female','woman','girl','soft','bright','sarah','emily','clara','lisa','anna'].some(x=>s.includes(x));const masc=['male','man','boy','deep','baritone','bass','john','david','james','alex'].some(x=>s.includes(x));const gender=fem&&!masc?'feminine':masc&&!fem?'masculine':'neutral';const voice=gender==='feminine'?'Kore':gender==='masculine'?'Algenib':'Zephyr';return{name,gender,basePitchHz:gender==='feminine'?215:gender==='masculine'?125:155,dominantTone:s.includes('calm')?'calm':s.includes('deep')?'deep':'professional',recommendedBaseVoice:voice,pitchShiftOffset:gender==='masculine'?-2:gender==='feminine'?1:0,speedFactor:1,resonanceFactor:1,breathiness:.12,timbreDescription:`${gender} natural acoustic vocal profile for ${name}.`,promptModifier:`Deliver speech with the distinctive cadence and natural warmth of ${name}.`};}
app.post('/api/voice-clone/analyze',async(req,res)=>{try{const{name,sampleBase64,mimeType='audio/webm',audioDurationSeconds=5,notes=''}=req.body;if(!name||typeof name!=='string')return res.status(400).json({error:'Voice name is required'});let profile:any=null;let providerVoiceId:string|undefined;let provider:'elevenlabs'|'gemini-profile'|'local'='local';
 if(getElevenLabsKey()&&sampleBase64){try{providerVoiceId=await elevenCreateClone(name.trim(),sampleBase64,mimeType,notes);provider='elevenlabs'}catch(error:any){console.error('[VoiceCraft] ElevenLabs clone creation failed:',error?.message||error)}}
 if(getGeminiApiKey()){try{const prompt=`Analyze the vocal characteristics of ${name}. Return only JSON with fields name, gender, basePitchHz, dominantTone, timbreDescription, recommendedBaseVoice, pitchShiftOffset, speedFactor, resonanceFactor, breathiness, promptModifier.`;const parts:any[]=[{text:prompt}];if(sampleBase64)parts.unshift({inlineData:{mimeType,data:sampleBase64}});const r=await getAI().models.generateContent({model:'gemini-3.1-flash-lite',contents:[{parts}],config:{responseMimeType:'application/json'}});if(r.text)profile=JSON.parse(r.text)}catch{}}
 profile||=heuristic(name.trim(),notes);res.json({success:true,profile:{id:`clone_${Date.now()}`,name:name.trim(),notes,createdAt:Date.now(),sampleDuration:audioDurationSeconds,...profile,provider,providerVoiceId},engine:provider});
 }catch(error:any){console.error('[VoiceCraft] voice clone error:',error?.message||error);res.status(502).json({success:false,error:'Voice clone creation failed. Check the clone provider configuration.'})}});

function userRecords(userId:string){if(!syncStore.has(userId))syncStore.set(userId,[]);return syncStore.get(userId)!}function devices(userId:string){if(!deviceStore.has(userId))deviceStore.set(userId,[]);return deviceStore.get(userId)!}
app.post('/api/sync/push',(req,res)=>{const{userId='user_default',deviceId='dev_unknown',records=[]}=req.body;const list=userRecords(userId);for(const r of records){const i=list.findIndex(x=>x.id===r.id);if(i>=0)list[i]={...r,deviceId,updatedAt:Date.now()};else list.push({...r,deviceId,updatedAt:Date.now()})}res.json({success:true,syncedCount:records.length,serverTotalCount:list.length,lastSyncedAt:Date.now()})});app.post('/api/sync/pull',(req,res)=>{const{userId='user_default',sinceTimestamp=0}=req.body;const list=userRecords(userId);res.json({success:true,records:list.filter(r=>r.updatedAt>sinceTimestamp),totalStored:list.length,serverTime:Date.now()})});app.get('/api/sync/devices',(req,res)=>{const userId=String(req.query.userId||'user_default');res.json({success:true,devices:devices(userId),crossPlatformSupported:['iOS','Android','macOS','Windows','Web'],e2eeStatus:'AES-256-GCM Active'})});app.post('/api/sync/devices/register',(req,res)=>{const{userId='user_default',deviceName='New Device',deviceType='desktop',appVersion='v2.4.0'}=req.body;const d={deviceId:`dev_${Date.now()}`,userId,deviceName,deviceType,lastSeen:Date.now(),ipMasked:'masked',appVersion};devices(userId).push(d);res.json({success:true,device:d})});app.post('/api/feedback/submit',(req,res)=>{const{userId='user_default',rating,message,category='general',audioClipId,telemetry={}}=req.body;if(!rating||!message)return res.status(400).json({error:'Rating and message are required'});const id=`fb_${Date.now()}`;feedbackStore.push({id,userId,rating:Number(rating),message,category,audioClipId,telemetry,createdAt:Date.now()});res.json({success:true,feedbackId:id})});app.get('/api/notifications',(req,res)=>{const userId=String(req.query.userId||'user_default');if(!notificationStore.has(userId))notificationStore.set(userId,[]);res.json({success:true,notifications:notificationStore.get(userId)!})});app.post('/api/notifications/mark-read',(req,res)=>res.json({success:true}));
export default app;
