import { ClonedVoiceProfile, ToneType } from '../types';
import { pocketTtsService } from './pocketTtsService';

const API_BASE_URL=(import.meta.env.VITE_API_URL||'https://voicecraft-api.vercel.app').replace(/\/$/,'');
export interface VoiceAnalysisResult{basePitchHz:number;dominantTone:ToneType;timbreDescription:string;recommendedBaseVoice:'Puck'|'Charon'|'Kore'|'Fenrir'|'Zephyr';pitchShiftOffset:number;speedFactor:number;resonanceFactor:number;breathiness:number;promptModifier:string;}
class VoiceCloneService{
 private mediaRecorder:MediaRecorder|null=null;private audioChunks:Blob[]=[];private audioContext:AudioContext|null=null;private analyserNode:AnalyserNode|null=null;private mediaStream:MediaStream|null=null;
 async startRecording(onFftData?:(data:Uint8Array)=>void,existingStream?:MediaStream|null){this.audioChunks=[];const stream=existingStream||(await navigator.mediaDevices.getUserMedia({audio:true}));this.mediaStream=stream;const AC=window.AudioContext||(window as any).webkitAudioContext;this.audioContext=new AC();const source=this.audioContext.createMediaStreamSource(stream);this.analyserNode=this.audioContext.createAnalyser();this.analyserNode.fftSize=256;source.connect(this.analyserNode);if(onFftData){const dataArray=new Uint8Array(this.analyserNode.frequencyBinCount);const update=()=>{if(this.analyserNode&&this.mediaRecorder?.state==='recording'){this.analyserNode.getByteFrequencyData(dataArray);onFftData(dataArray);requestAnimationFrame(update);}};requestAnimationFrame(update);}const mimeType=MediaRecorder.isTypeSupported('audio/webm')?'audio/webm':'audio/ogg';this.mediaRecorder=new MediaRecorder(stream,{mimeType});this.mediaRecorder.ondataavailable=e=>{if(e.data.size>0)this.audioChunks.push(e.data)};this.mediaRecorder.start(100);}
 async stopRecording(durationSec=5){return new Promise<{blob:Blob;durationSec:number;base64:string}>((resolve,reject)=>{if(!this.mediaRecorder){reject(new Error('MediaRecorder not active'));return;}this.mediaRecorder.onstop=()=>{const mimeType=this.mediaRecorder?.mimeType||'audio/webm';const blob=new Blob(this.audioChunks,{type:mimeType});this.mediaStream?.getTracks().forEach(t=>t.stop());if(this.audioContext&&this.audioContext.state!=='closed')this.audioContext.close();const reader=new FileReader();reader.onloadend=()=>resolve({blob,durationSec,base64:(reader.result as string).split(',')[1]||''});reader.onerror=reject;reader.readAsDataURL(blob)};this.mediaRecorder.stop()});}
 async analyzeAndClone(name:string,sampleBlob?:Blob,sampleBase64?:string,notes=''):Promise<ClonedVoiceProfile>{
   if(!sampleBlob) throw new Error('A voice recording is required to create a real clone.');
   const voiceKey=`${name}_${Date.now()}`;
   let pocketClone:{voiceId:string;sampleRate:number};
   try{pocketClone=await pocketTtsService.cloneVoice(sampleBlob,voiceKey);}catch(error){const message=error instanceof Error?error.message:String(error);throw new Error(`Real browser voice cloning failed: ${message}`);}

   let profileData:any=null;
   if(navigator.onLine&&sampleBase64){try{const res=await fetch(`${API_BASE_URL}/api/voice-clone/analyze`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,sampleBase64,mimeType:sampleBlob.type||'audio/webm',audioDurationSeconds:5,notes})});if(res.ok){const data=await res.json();if(data.success&&data.profile)profileData=data.profile;}}catch{}}

   return {id:profileData?.id||`clone_${Date.now()}`,name:profileData?.name||name,type:'cloned',gender:profileData?.gender||'neutral',tone:profileData?.dominantTone||'professional',baseVoice:profileData?.recommendedBaseVoice||'Zephyr',description:profileData?.timbreDescription||`Browser-cloned voice for ${name}`,avatarColor:this.getRandomAvatarGradient(),pitchShift:profileData?.pitchShiftOffset||0,speedFactor:profileData?.speedFactor||1,warmth:profileData?.resonanceFactor?Math.min(1,profileData.resonanceFactor*.7):.8,breathiness:profileData?.breathiness||.1,basePitchHz:profileData?.basePitchHz||160,timbreDescription:profileData?.timbreDescription||'Voice cloned locally in the browser with Pocket TTS.',promptModifier:profileData?.promptModifier||'Speak naturally using the cloned reference voice.',sampleDuration:profileData?.sampleDuration||5,notes,createdAt:Date.now(),provider:'pocket-tts',providerVoiceId:pocketClone.voiceId,providerSampleBase64:sampleBase64,providerSampleMimeType:sampleBlob.type||'audio/webm'};
 }
 private localProfile(name:string,notes:string):ClonedVoiceProfile{throw new Error(`A real clone could not be created for ${name}.`)}
 private getRandomAvatarGradient(){const gradients=['from-cyan-500 to-blue-600','from-violet-500 to-purple-800','from-rose-500 to-pink-700','from-amber-500 to-red-700','from-emerald-500 to-teal-800','from-fuchsia-500 to-indigo-700'];return gradients[Math.floor(Math.random()*gradients.length)]}
}
export const voiceCloneService=new VoiceCloneService();
