import { ClonedVoiceProfile, ToneType } from '../types';

const API_BASE_URL=(import.meta.env.VITE_API_URL||'https://voicecraft-api.vercel.app').replace(/\/$/,'');
export interface VoiceAnalysisResult{basePitchHz:number;dominantTone:ToneType;timbreDescription:string;recommendedBaseVoice:'Puck'|'Charon'|'Kore'|'Fenrir'|'Zephyr';pitchShiftOffset:number;speedFactor:number;resonanceFactor:number;breathiness:number;promptModifier:string;}
class VoiceCloneService{
 private mediaRecorder:MediaRecorder|null=null;private audioChunks:Blob[]=[];private audioContext:AudioContext|null=null;private analyserNode:AnalyserNode|null=null;private mediaStream:MediaStream|null=null;
 async startRecording(onFftData?:(data:Uint8Array)=>void,existingStream?:MediaStream|null){this.audioChunks=[];const stream=existingStream||(await navigator.mediaDevices.getUserMedia({audio:true}));this.mediaStream=stream;const AC=window.AudioContext||(window as any).webkitAudioContext;this.audioContext=new AC();const source=this.audioContext.createMediaStreamSource(stream);this.analyserNode=this.audioContext.createAnalyser();this.analyserNode.fftSize=256;source.connect(this.analyserNode);if(onFftData){const dataArray=new Uint8Array(this.analyserNode.frequencyBinCount);const update=()=>{if(this.analyserNode&&this.mediaRecorder?.state==='recording'){this.analyserNode.getByteFrequencyData(dataArray);onFftData(dataArray);requestAnimationFrame(update);}};requestAnimationFrame(update);}const mimeType=MediaRecorder.isTypeSupported('audio/webm')?'audio/webm':'audio/ogg';this.mediaRecorder=new MediaRecorder(stream,{mimeType});this.mediaRecorder.ondataavailable=e=>{if(e.data.size>0)this.audioChunks.push(e.data)};this.mediaRecorder.start(100);}
 async stopRecording(durationSec=5){return new Promise<{blob:Blob;durationSec:number;base64:string}>((resolve,reject)=>{if(!this.mediaRecorder){reject(new Error('MediaRecorder not active'));return;}this.mediaRecorder.onstop=()=>{const mimeType=this.mediaRecorder?.mimeType||'audio/webm';const blob=new Blob(this.audioChunks,{type:mimeType});this.mediaStream?.getTracks().forEach(t=>t.stop());if(this.audioContext&&this.audioContext.state!=='closed')this.audioContext.close();const reader=new FileReader();reader.onloadend=()=>resolve({blob,durationSec,base64:(reader.result as string).split(',')[1]||''});reader.onerror=reject;reader.readAsDataURL(blob)};this.mediaRecorder.stop()});}
 async analyzeAndClone(name:string,sampleBlob?:Blob,sampleBase64?:string,notes=''):Promise<ClonedVoiceProfile>{if(navigator.onLine){try{const res=await fetch(`${API_BASE_URL}/api/voice-clone/analyze`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,sampleBase64,mimeType:sampleBlob?.type||'audio/webm',audioDurationSeconds:5,notes})});const data=await res.json();if(data.success&&data.profile){return{id:data.profile.id||`clone_${Date.now()}`,name:data.profile.name,type:'cloned',gender:data.profile.gender||'neutral',tone:data.profile.dominantTone||'professional',baseVoice:data.profile.recommendedBaseVoice||'Zephyr',description:data.profile.timbreDescription||`Voice clone profile for ${name}`,avatarColor:this.getRandomAvatarGradient(),pitchShift:data.profile.pitchShiftOffset||0,speedFactor:data.profile.speedFactor||1,warmth:data.profile.resonanceFactor?Math.min(1,data.profile.resonanceFactor*.7):.8,breathiness:data.profile.breathiness||.1,basePitchHz:data.profile.basePitchHz||160,timbreDescription:data.profile.timbreDescription||'',promptModifier:data.profile.promptModifier||'',sampleDuration:data.profile.sampleDuration||5,notes,createdAt:Date.now(),provider:data.profile.provider||'gemini-profile',providerVoiceId:data.profile.providerVoiceId};}}catch{}}return this.localProfile(name,notes);}
 private localProfile(name:string,notes:string):ClonedVoiceProfile{return{id:`clone_local_${Date.now()}`,name,type:'cloned',gender:'neutral',tone:'professional',baseVoice:'Zephyr',description:`Local voice profile for ${name}`,avatarColor:this.getRandomAvatarGradient(),pitchShift:0,speedFactor:1,warmth:.85,breathiness:.12,basePitchHz:160,timbreDescription:`Fallback acoustic profile for ${name}.`,promptModifier:`Deliver text with the speech style and vocal cadence of ${name}.`,sampleDuration:5,notes,createdAt:Date.now(),provider:'local'};}
 private getRandomAvatarGradient(){const gradients=['from-cyan-500 to-blue-600','from-violet-500 to-purple-800','from-rose-500 to-pink-700','from-amber-500 to-red-700','from-emerald-500 to-teal-800','from-fuchsia-500 to-indigo-700'];return gradients[Math.floor(Math.random()*gradients.length)]}
}
export const voiceCloneService=new VoiceCloneService();
